

<?php $isFixed = Mage::getStoreConfig('carriers/speedyshippingmodule/fixed_pricing_enable'); ?>
    <?php $output = null; ?>
    <?php if ($this->_codAmount && !$isFixed && !$this->_isFreeMethod){
        
    
        $output .='<p>'.$this->__('Speedy Payment method tax');
        
         $_excl = $this->_codAmount;
         $_incl = $this->_codAmountWithTaxApplied;
         $output .= $_excl.' лв.';
         if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl){
            $output .=' ('.$this->__('Incl. Tax').' ' .$_incl.' лв.)';
         }
        
        $output .= '</p>';
    }
    
    if($output){
        echo $output;
    }
    ?>